export const DASHBOARDS = [
  {
    id:          'wes-lab',
    title:       'Laboratory Wastewater Surveillance Assessment',
    subtitle:    'WES Management Support Team',
    description: 'Assess country wastewater surveillance situation for outbreak response. Data collected from WHO African Region Member States.',
    tags:        ['Laboratory', 'Wastewater', 'Surveillance'],
    version:     '2025v1',
    countries:   3,
    sites:       27,
    route:       '/wes-lab',
    accent:      '#009FDB',
  },
  {
    id:          'wes-subnational',
    title:       'Sub-National Wastewater Surveillance Assessment',
    subtitle:    'WES Management Support Team',
    description: 'Assess sub-national wastewater surveillance capacity at province and site level across WHO African Region Member States.',
    tags:        ['Sub-National', 'Wastewater', 'Surveillance'],
    version:     '2025v1',
    countries:   2,
    sites:       75,
    route:       '/wes-subnational',
    accent:      '#C87DA8',
  },
  {
    id:          'wes-national',
    title:       'National Wastewater Surveillance Assessment',
    subtitle:    'WES Management Support Team',
    description: 'Assess national wastewater surveillance capacity across WHO African Region Member States.',
    tags:        ['National', 'Wastewater', 'Surveillance'],
    version:     '2025v1',
    countries:   3,
    sites:       50,
    route:       '/wes-national',
    accent:      '#6B3FA0',
  },
  {
    id:          'coming-soon-1',
    title:       'Epidemiological Surveillance Dashboard',
    subtitle:    'Disease Intelligence Unit',
    description: 'Track and analyse epidemiological trends across African Region Member States.',
    tags:        ['Epidemiology', 'Surveillance'],
    version:     'Coming Soon',
    countries:   null,
    sites:       null,
    route:       null,
    accent:      '#6B3FA0',
  },
  {
    id:          'coming-soon-2',
    title:       'Vaccine Coverage & Cold Chain',
    subtitle:    'Immunization Programme',
    description: 'Monitor vaccination coverage rates and cold chain integrity across distribution networks.',
    tags:        ['Vaccines', 'Cold Chain'],
    version:     'Coming Soon',
    countries:   null,
    sites:       null,
    route:       null,
    accent:      '#C87DA8',
  },
];
